# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d46eb1626a47a070ab0052a008c8ca3ff7a86ca6c9e0b9c10c7d39385477de7102b5646c5d1d079be77687344c9a928e1e9b257978a69b99f81e73f247f892

test:
  secret_key_base: 95a85159e2ff2a8d99c7cf94b14d65948993d170a60ff72cf8c2a71856e0ff4d86c753545921d1a5a349315168a4c845c25c3f16058e26d03864f27a41748a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
